# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vasko Zdravevski
email: vzdravevski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I write about software
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.vaskoz.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vaskoz
github_username:  vaskoz

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
exclude:
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

paginate: 5 # amount of posts to show
paginate_path: /page:num/
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-89786508-1"

